# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Practice' do
  # Comment the next line if you don't want to use dynamic frameworks
  pod 'RxSwift'
  pod 'RxCocoa'

  # Pods for Practice

  target 'PracticeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PracticeUITests' do
    # Pods for testing
  end

end
