# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Practice_RxSwift' do
pod 'RxSwift'
pod 'RxCocoa'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Practice_RxSwift

  target 'Practice_RxSwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Practice_RxSwiftUITests' do
    # Pods for testing
  end

end
